### ISSUE TITLE
cannot compile the examples against ppx_bitstring from opam

### ISSUE THREAD

**Issue by martindemello** [nojb/bitstring-ppx#5]
I copied the gif example into its own project and attempted to compile it against ppx_bitstring from opam. It failed in both 4.02 and 4.03, with different error messages:

```
[using ocaml-4.02.3 + ppx_bitstring 1.0.0] $ make
ocamlbuild -use-ocamlfind gif.native
+ ocamlfind ocamlc -c -g -thread -package bitstring -package ppx_bitstring -o gif.cmo gif.ml
File "gif.ml", line 13, characters 8-17:
Uninterpreted extension 'bitstring'.
Command exited with code 2.
Compilation unsuccessful after building 2 targets (0 cached) in 00:00:00.
make: *** [gif] Error 10

```
and
```
[using ocaml-4.03.0 + ppx_bitstring 1.3.2] $ make
ocamlbuild -use-ocamlfind gif.native
+ ocamlfind ocamldep -package bitstring -package ppx_bitstring -modules gif.ml > gif.ml.depends
File "gif.ml", line 14, characters 4-443:
Wrong pattern type
Command exited with code 2.
Compilation unsuccessful after building 1 target (0 cached) in 00:00:00.
make: *** [gif] Error 10
```

you can see the full repo here: https://github.com/martindemello/test_ppx_bitstring

**Comment by nojb** [comment]
Hi @martindemello, thanks for the report!  I will give it a closer look later today, but note that the `ppx_bitstring` opam package is not this one.  Maybe https://github.com/xguerin/ppx_bitstring, but I am not sure (and I believe they use a completely different concrete syntax).  Our package was actually renamed `bitstring-ppx` to avoid the name clash.  I will be cutting a release into `opam` shortly.  In any case if you pin it you should be able to build your example with

    ocamlfind ocamlc -package bitstring-ppx.ppx gif.ml

**Comment by martindemello** [comment]
oops, not sure how i made that mistake :) sorry for the noise; i'll file against the correct project

**Comment by nojb** [comment]
OK, but note that the file `gif.ml` from this project will not compile with the other project, as they use completely different concrete syntaxes :(

**Comment by martindemello** [comment]
that's unfortunate indeed :( i'll give them both a try and see which one feels nicer to use.
